---
# Defaults for inventory
platform: ios

data:
  ntp_server: 8.8.8.8

connection_options:
  scrapli:
    extras:
      auth_strict_key: false # skip in lab environment
  netmiko:
    extras:
      global_delay_factor: 2 # increase delay factor for lab environment
  napalm:
    extras:
      optional_args:
        transport: ssh
