---
core1:
  hostname: 192.168.121.101
  platform: cisco_iosxe
  groups: [lab, core]
dist1:
  hostname: 192.168.121.102
  platform: arista_eos
  groups: [lab, dist]
dist2:
  hostname: 192.168.121.103
  platform: arista_eos
  groups: [lab, dist]
acc1:
  hostname: 192.168.121.104
  platform: cisco_iosxe
  groups: [lab, access]
acc2:
  hostname: 192.168.121.105
  platform: cisco_iosxe
  groups: [lab, access]
