---
R1:
  hostname: 192.168.121.101
  groups:
    - uk_site
  data:
    ntp_server: 1.1.1.1
R2:
  hostname: 192.168.121.102
  groups:
    - usa_site
R3:
  hostname: 192.168.121.103
  groups:
    - uk_site
R4:
  hostname: 192.168.121.104
  groups:
    - usa_site
